config/routes.rb
Osp::Application.routes.draw do

  resources :videos

  resources :pliks

resources :users, :user_sessions, :news, :images, :statistics, :members, :albums

match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout
match 'logowanie' => 'user_sessions#new', :as => :login
match 'rejestracja' => 'users#new'
match 'about' => 'users_#about'
match 'czlonkowie' => 'users_#czlonkowie'
match 'galeria' => 'users_#galeria'
match 'galeria_wszystkie' => 'albums#galeria_wszystkie'
match 'aktualnosci' => 'news#index'
match 'aktualnosci_grupuj' => 'news#group'
match 'imprezy' => 'news#imprezy'
match 'interwencje' => 'news#interwencje'
match 'statystyki' => 'statistics#index'
match 'szkolenia' => 'news#szkolenia'
match 'inne' => 'news#inne'
match 'otwp' => 'news#otwp'
match 'wynajem_sali' => 'users#wynajem_sali'
match '/ftp/upload' => 'images#create'
match '/pozar_plus' => 'statistics#pozar_plus'
match '/pozar_minus' => 'statistics#pozar_minus'
match '/zagrozenia_plus' => 'statistics#zagrozenia_plus'
match '/zagrozenia_minus' => 'statistics#zagrozenia_minus'
match '/alarmy_plus' => 'statistics#alarmy_plus'
match '/alarmy_minus' => 'statistics#alarmy_minus'

root :to => "users_#start"

end

app/models/user.rb
class User < ActiveRecord::Base
acts_as_authentic
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      if (current_user.username == 'Administrator'&&current_user.id==1)
        @users = User.all
        @statystyki = Statistic.find_by_rok(Time.now.year)

        respond_to do |format|
          format.html
          format.json { render json: @users }
        end
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

  def new
   if current_user
    redirect_to root_url, :notice => 'Informacja! Wyloguj si&#281; aby dokona&#263; rejestracji'
   else
    redirect_to root_url, :notice => 'Informacja! Rejestracja zosta&#322;a wy&#322;&#261;czona'
   end
   #@user = User.new
   #@statystyki = Statistic.find_by_rok(Time.now.year)

    #respond_to do |format|
      #format.html # new.html.erb
      #format.json { render json: @user }
    #end
  end

  def edit
    if current_user
      @user = User.find(params[:id])
      if (current_user.username == 'Administrator'&&current_user.id==1)
        @statystyki = Statistic.find_by_rok(Time.now.year)
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

  def create
    redirect_to root_url, :notice => 'Informacja! Rejestracja zosta&#322;a wy&#322;&#261;czona'
    #@user = User.new(params[:user])

    #respond_to do |format|
      #if @user.save
        #format.html { redirect_to( root_url, :notice => 'Informacja! Konto zarejestrowane!') }
        #format.xml { render :xml => @user, :status => :created, :location => @user }
      #else
        #format.html { render :action => "new" }
        #format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      #end
    #end
  end

  def update
   if current_user
     @user = User.find(params[:id])
     if (current_user.username == 'Administrator'&&current_user.id==1)

       respond_to do |format|
         if @user.update_attributes(params[:user])
           format.html { redirect_to @user, notice: 'User was successfully updated.' }
           format.json { head :no_content }
         else
           format.html { render action: "edit" }
           format.json { render json: @user.errors, status: :unprocessable_entity }
         end
       end
     else
       redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
     end
   else
     redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
   end
  end

  def destroy
    if current_user
      @user = User.find(params[:id])
      if (current_user.username == 'Administrator'&&current_user.id==1)
        @user.destroy

        respond_to do |format|
          format.html { redirect_to users_url }
          format.json { head :no_content }
        end
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

 def start
    @news = News.last(6).sort_by(&:created_at).reverse
    @statystyki = Statistic.find_by_rok(Time.now.year)
    if @statystyki == nil
      @statystyki = Statistic.new
      @statystyki.rok = Time.now.year
      @statystyki.pozary = 0
      @statystyki.zagrozenia = 0
      @statystyki.falarmy = 0
      @statystyki.save
    end

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

 def galeria
    @albums = Album.page(params[:page]).per_page(7).order("created_at DESC")
    @zdjecia = Image.all.sort_by(&:created_at).reverse
    @zdjecia_page = Image.page(params[:page]).per_page(9).order("created_at DESC")
    @statystyki = Statistic.find_by_rok(Time.now.year)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

 def about
    @statystyki = Statistic.find_by_rok(Time.now.year)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

 def czlonkowie
    @member = Member.new
    @members = Member.all
    @statystyki = Statistic.find_by_rok(Time.now.year)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

 def wynajem_sali
    @statystyki = Statistic.find_by_rok(Time.now.year)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
    <div id="error_explanation">
    <% if  (@user.errors.count) == 1  %>
      <h2>Użytkownik nie został stworzony z powodu jednego błędu</h2>
    <% elsif (@user.errors.count) > 1 %>
        <h2>Użytkownik nie został stworzony z powodu <%= @user.errors.count %> błędów</h2>
    <% end %>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="field">
  <%= f.label :Nazwa_Użytkownika %>
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
 <div class="field">
  <%= f.label :hasło %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :Potwierdź_hasło %>
  <%= f.password_field :password_confirmation %>
</div>
<br />
 <div class="actions">
     <%= f.submit :value => 'Zrejestruj', "style" => "height:35px;width:100px;font-weight:bold;cursor:pointer;" %>
</div>
<% end %>

app/views/users/about.html.erb
<div class="home">
<h4>Historia Jednostki</h4>
<div style="background: none repeat scroll 0% 0% rgb(116, 149, 150);color:black;padding: 5px 19px 0px 18px;">
<%= image_tag("https://lh5.googleusercontent.com/--AxcXFN5xFA/SWngobLEaxI/AAAAAAAAAJs/eOHofSn8NBg/s750/skanuj0041.jpg", :class => "his_img") %>
<br>Ochotnicza Straż Pożarna w Leśniewie została zorganizowana w 1882 roku pod zaborem pruskim.
W tym czasie niemcy nakładali obowiązek czuwania nad ochroną mienia na wszystkich obywateli  w wieku od 18-tego roku życia.
Ówczesna straż działała na zasadach przymusu, rolnicy obowiązani byli do podstawiania zaprzęgów konnych do przewozu beczkowozów.
Taki stan trwał do chwili odzyskania przez nasz kraj niepodległości.<br>
<br>
Jak wynika z relacji ojców, ludzi starszych na terenie wsi Leśniewa – założenie straży przymusowej przypada w 1882roku. 
Jednak nie pamięta się pierwszych założycieli. <br>Od 1930 do 1939 funkcje Prezesa pełnił Jan Potrykus, zaraz po wyzwoleniu 1945 r. Prezesem był Feliks Pieper, Józef Cieślak, Jan Czapp, a 15-03-1971 r wybrany został Władysław Grzywacz miejscowy leśniczy, od 29-12-1995 r.  do chwili obecnej jest Wincenty Lanc.<br>
<br>
            Pierwsza remiza strażacka to drewniana chatka usytuowana  przy wiejskim stawie i drodze wiejskiej.( widoczna na zdjęciu w książce „ Ziemia Pucka na dawnych pocztówkach”). Remiza ta rozebrana została w 1948 r. i pobudowano druga z drugiej strony stawu która stoi do dziś.
<br><br>
W 1973 roku zapada decyzja o budowie następnej remizy.14-12-1973 r. powstaje społeczny komitet budowy na czele stoi Władysław Grzywacz a zastępcami Władysław Srok i Proena Stefan Srok Teofil. Budowę rozpoczęto ze środków pozyskanych z różnych firm i instytucji a robotę wykonywano społecznie. Budowę zakończono w 1977r. W następnych latach modernizowano (budowa kotłowni, sanitariatów, biura, CO ).
<br><br>
            Dla rozszerzenia działalności kulturalnej i sportowej strażaków i nie tylko- buduje się przy remizie w 1999r. boisko utwardzone asfaltem do piłki ręcznej i koszykówki oraz buduje się pierwszy w gminie amfiteatr.
<br><br>
Sprzęt do gaszenia pożarów znajdował się w stałej sprawnej gotowości bojowej. Na dźwięk syren rolnicy podstawiali zaprzęgi konne do zaopatrzonych w sprzęt pożarniczy powozów które były na stanie w remizach. Dnia 30-05-1971  roku OSP otrzymało pierwszy samochód strażacki z pełnym wyposażeniem. Kierowcą i opiekunem samochodu bojowego został druh Bronisław Cieślak obowiązki te pełni nieprzerwanie do dziś ( 33 lat ), odznaczony „Złotym Znakiem Związku”. Od 1982 do1997 r. posiadaliśmy dwa samochody strażackie ze względu na bardzo częste pożary lasów.   
<br><br>
OSP w Leśniewie zawsze posiadała dobrą zorganizowana straż, silny trzon kierowniczy i działający aktyw strażacki, w konsekwencji czego straż z każdym rokiem  uzyskuje wyższy poziom szkolenia bojowego i sportowego. Zwycięstwa w zawodach bojowych na szczeblu powiatu a w 1988 r. pierwsze miejsce w województwie drużyn młodzieżowych. Podczas prowadzenia klasyfikacji współzawodnictwa wiele razy byliśmy najlepsi w gminie, a w 1988 i 1989 roku uzyskiwaliśmy trzecie miejsce w województwie.
<br><br>
            W dowód uznania tej tak szeroko zakrojonej działalności z całą przyjemnością należy podkreślić iż sztandar zakupiony i ufundowany z dobrowolnych składek mieszkańców wsi stanowi dowód wysokiego uznania działalności OSP przez lokalną ludność. Przekazanie sztandaru dla strażaków odbyło się 22-07-1982 r. w setną rocznicę działalności straży przez lokalną społeczność. Poświęcenia sztandaru dokonał ks. Proboszcz Zbigniew Krzewina w dniu 03-10-1982 r. OSP Leśniewo zostało odznaczone srebrnym medalem za zasługi dla pożarnictwa w 1997 r.
<br><br></div>
</div>

app/views/users/czlonkowie.html.erb
<div class="home">
<h4>Struktura OSP Leśniewo</h4>
<div style="background: none repeat scroll 0% 0% rgb(116, 149, 150);color:black;display:block;padding: 5px 19px 0px 18px;min-height:500px;">
<br>
<div style="display:inline-block;width:50%;height:500px;float:left;">
<center><h4>Zarząd</h4></center>
<% @members.each do |member| %>
<% if member.stanowisko != "Członek OSP" %>
<center><span class="label label-inverse"><%= member.stanowisko %></span> <font id="czlonkowie_lista"><%= member.nazwa %></font>
  <% if current_user && ((current_user.username == "Administrator" && current_user.id == 1)||(current_user.username == "strazak"&& current_user.id == 2)) %>
	<%= link_to '[x]', member, method: :delete, data: { confirm: "Czy napewno chcesz usunąć '#{member.nazwa}'?" } %>
  <% end %>
</center>
<% end %>
<% end %>
</div>
<div style="display:inline-block;width:49%;margin-left:0px;margin-bottom:50px;border-left:2px solid;border-color:rgb(16, 34, 35);">
<center><h4>Członkowie</h4></center>
<% @members.each do |member| %>
<% if member.stanowisko == "Członek OSP" %>
<center><font id="czlonkowie_lista"><%= member.nazwa %></font>
  <% if current_user && ((current_user.username == "Administrator" && current_user.id == 1)||(current_user.username == "strazak"&& current_user.id == 2)) %>
  <%= link_to '[x]', member, method: :delete, data: { confirm: "Czy napewno chcesz usunąć '#{member.nazwa}'?" } %>
  <% end %>
</center>
<% end %>
<% end %>
</div>
<% if current_user && ((current_user.username == "Administrator" && current_user.id == 1)||(current_user.username == "strazak"&& current_user.id == 2)) %>
<%= form_for Member.new do |f| %>
  <%= f.label :Imie_i_Nazwisko %>
  <%= f.text_field :nazwa, :width => "160px" %>
  <%= f.select(:stanowisko, options_for_select([['Prezes', 'Prezes'], ['V-ce Prezes', 'V-ce Prezes'], ['Naczelnik OSP', 'Naczelnik OSP'], ['Sekretarz', 'Sekretarz'], ['Skarbnik', 'Skarbnik'], ['Gospodarz', 'Gospodarz'], ['Członek Zarządu', 'Członek Zarządu'], ['Członek OSP', 'Członek OSP']]), {}, {:style =>"width:180px;height:40px;font-size:20px;"}) %>
  <%= f.submit "Dodaj","style" => "height:35px;width:100px;font-weight:bold;cursor:pointer;margin-top:-10px;" %>
<% end %>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/galeria.html.erb
<div class="gallery">
   			       <div class="gallery_div"> 
					<h4 style="float:left;">Galeria</h4>
<ul style="float:left;margin-left:20px;height:35px;margin-top:6.5px;">
<%= link_to "Albumy", "/galeria", :class => "zakladki_male" %>
<%= link_to "Wszystkie", "/galeria_wszystkie", :class => "zakladki_male" %>
<%= image_tag("/assets/gplus.png", :height => '47', :width => '42', :class =>"galeriaplus", :onclick => "window.open('https://plus.google.com/101678126146835185818/posts','external');return false;", :title => "Galeria na Picasa Web") %>
</ul>
					<ul>
					<%= will_paginate @albums, :container => false %>
					</ul>
				</div>
					<% @albums.each do |album| %>
<% @zdjecie_pierwsze = Image.find_all_by_przydzial(album.nr_newsa.to_s).first %>
<% @fotki = Image.find_all_by_przydzial(album.nr_newsa.to_s).first(5) %>
<% @numer = Image.find_all_by_przydzial(album.nr_newsa.to_s).count %>
<% if @zdjecie_pierwsze != nil %>
<div class="album_list" style="background:url(http://serwer.osp-lesniewo.pl/<%= @zdjecie_pierwsze.nazwa %>); background-size: 100%;" onclick="location.href = '/albums/<%= album.id %>'">
<% else %>
<div class="album_list" onclick="location.href = '/albums/<%= album.id %>'" %>
<% end %>
<% if current_user && ((current_user.username == "Administrator" && current_user.id == 1)||(current_user.username == "strazak"&& current_user.id == 2)) %>
<%= link_to album, method: :delete, data: { confirm: 'Czy napewno chcesz usunąć ten album?' }, "style"=>"position:relative;float:right;", :class=>"btn btn-mini btn-danger" do %>
<i class="icon-trash"></i>
<% end %>
<% end %>

Opublikowano: <%= album.created_at.strftime("%H:%M %d-%m-%Y") %>

<div class="album_inside">
<div style="display: block;">
<%= album.tytul[0..45] %> (<%= @numer  %>
<% if @numer.to_s.last(1) == "1" %>
zdjęcie
<% elsif @numer.to_s.last(1) == "2" || @numer.to_s.last(1) == "3" || @numer.to_s.last(1) == "4" %>
zdjęcia
<% else %>
zdjęć
<% end %>)
</div>
<% @fotki.each do |fotka| %>
<%= image_tag("http://serwer.osp-lesniewo.pl/#{fotka.nazwa}", :class=>"img-rounded", "style"=>"margin-right:5px") %>
<% end %>
</div>
</div>
					<% end %>
<% if current_user && current_user.username == "Administrator" %>
<%= form_for Album.new do |f| %>
  <%= f.label :Tytuł_albumu %>
  <%= f.text_field :tytul, :width => "160px" %>
  <%= f.submit "Dodaj","style" => "height:35px;width:100px;font-weight:bold;cursor:pointer;margin-top:-10px;" %>
<% end %>
<% end %>
			</div>

app/views/users/index.html.erb
<h4>Listing users</h4>
 
<table>
<tr>
<th>Username</th>
<th>Email</th>
<th></th>
<th></th>
<th></th>
</tr>
 
<% @users.each do |user| %>
<tr>
<td><%= user.username %></td>
<td><%= user.email %></td>
<td><%= link_to 'Show', user %></td>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="home">
<h4>Rejestracja</h4>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%= @user.crypted_password %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_salt %>
</p>

<p>
  <b>Persistence token:</b>
  <%= @user.persistence_token %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/start.html.erb
<div class="home">
<h4>Ostatnio Dodane Aktualności <%= image_tag("rss.png","title" => "Subskrypcja Aktualności", :class => "przycisk_rss", :onclick => "window.open('/news.atom','external');return false;") %></h4>
  <ul>
    <% @news.each do |news| %>
    <% @images = Image.find_all_by_przydzial(news.id.to_s) %>
    <% @logo = Image.find_all_by_przydzial(news.id.to_s).first %>
    <li class="news_start">
      <% if @images.count == 0 %>
      <div style="position:absolute; left:45px; bottom:15px;">
      <% if news.rodzaj == "Imprezy" %>
      <%= image_tag("bookmars_blue.png", :class => "bookmars", "title" => "Kategoria: Impreza") %>
      <% elsif news.rodzaj == "Interwencje" %>
            <%= image_tag("bookmars_red.png", :class => "bookmars", "title" => "Kategoria: Interwencja") %>
      <% elsif news.rodzaj == "Szkolenia" %>
            <%= image_tag("bookmars_green.png", :class => "bookmars", "title" => "Kategoria: Szkolenie") %>
      <% elsif news.rodzaj == "Inne" %>
            <%= image_tag("bookmars_black.png", :class => "bookmars", "title" => "Kategoria: Inne") %>
      <% elsif news.rodzaj == "OTWP" %>
            <%= image_tag("bookmars_orange.png", :class => "bookmars", "title" => "Kategoria: OTWP") %>
      <% end %>
      </div>
      <%= link_to("/news/#{news.id}") do %>
      <%= image_tag("icon-logo.jpg", :class => "start_logo") %><% end %>
      <% else %>
      <%= link_to("/news/#{news.id}") do %>
      <%= image_tag("http://serwer.osp-lesniewo.pl/#{@logo.nazwa}", :class=>"glowna_miniatura") %><% end %>
      <div style="position:absolute; left:45px; bottom:15px;">
      <% if news.rodzaj == "Imprezy" %>
      <%= image_tag("bookmars_blue.png", :class => "bookmars", "title" => "Kategoria: Impreza") %>
      <% elsif news.rodzaj == "Interwencje" %>
            <%= image_tag("bookmars_red.png", :class => "bookmars", "title" => "Kategoria: Interwencja") %>
      <% elsif news.rodzaj == "Szkolenia" %>
            <%= image_tag("bookmars_green.png", :class => "bookmars", "title" => "Kategoria: Szkolenie") %>
      <% elsif news.rodzaj == "Inne" %>
            <%= image_tag("bookmars_black.png", :class => "bookmars", "title" => "Kategoria: Inne") %>
      <% elsif news.rodzaj == "OTWP" %>
            <%= image_tag("bookmars_orange.png", :class => "bookmars", "title" => "Kategoria: OTWP") %>
      <% end %>
      </div>
      <% end %>
      <div>
        <h3><%= news.tytul.gsub(/^([a-z])/) { $1.capitalize }[0..22]+' ...' %></h3>
        <% if (((Time.now - news.created_at).to_i / 60) / 60) > 24  %>
          <span style="margin-top:-5px;color: rgb(230, 230, 230);"><i class="icon-calendar"></i> Opublikowano <%= news.created_at.strftime("%d-%m-%Y %H:%M") %></span>
        <% else %>
          <span style="margin-top:-5px;color: rgb(109, 242, 252);"><i class="icon-calendar"></i> Opublikowano <%= time_ago_in_words(news.created_at) + ' temu' %></span>
        <% end %>
        <span >
          <%= link_to news_url(news, :anchor => "disqus_thread"), :"data-disqus-identifer" => news.id, "style" => "width:100%;color:white;" do %>
            <i class="icon-comment"></i> ##
          <% end %>
        </span>
        <p>
          <%= (strip_tags(news.tresc))[0..230]+"..." %>
        </p>
        <%= link_to 'Czytaj więcej »', news, class: "label label-important", id: "start_a" %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  var disqus_shortname = '<%= ENV['disqus_shortname'] %>';

  if (disqus_shortname.length > 0) {
    (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
  }
</script>

app/views/users/wynajem_sali.erb
    <script type='text/javascript' src='http://www.pixedelic.com/plugins/camera/development/camera_1.0.6/scripts/jquery.min.js'></script>
    <script type='text/javascript' src='http://www.pixedelic.com/plugins/camera/development/camera_1.0.6/scripts/jquery.mobile.customized.min.js'></script>
    <script type='text/javascript' src='http://www.pixedelic.com/plugins/camera/development/camera_1.0.6/scripts/jquery.easing.1.3.js'></script> 
    <script type='text/javascript' src='http://www.pixedelic.com/plugins/camera/development/camera_1.0.6/scripts/camera.min.js'></script> 
    
    <script>
		jQuery(function(){
			jQuery('#camera_wrap_2').camera({
				height: '400px',
				pagination: false,
				thumbnails: true
			});
		});
	</script>
<div class="about">
<h4>Wynajem Sali</h4>
<div style="background: none repeat scroll 0% 0% rgb(116, 149, 150);color:black;">
    <div class="fluid_container">
        <div class="camera_wrap camera_black_skin" id="camera_wrap_2">
            <div data-thumb="/assets/sala/thumbs/IMG_9460.JPG" data-src="/assets/sala/IMG_9460.JPG">
            </div>
            <div data-thumb="/assets/sala/thumbs/IMG_9475.JPG" data-src="/assets/sala/IMG_9475.JPG">
                <div class="camera_caption fadeFromBottom">
                    Do dyspozycji jest ruchoma scena..
                </div>
            </div>
            <div data-thumb="/assets/sala/thumbs/IMG_9476.JPG" data-src="/assets/sala/IMG_9476.JPG">
            </div>
            <div data-thumb="/assets/sala/thumbs/IMG_9478.JPG" data-src="/assets/sala/IMG_9478.JPG">
		<div class="camera_caption fadeFromBottom">
                    Sala jest doskonale oświetlona..
                </div>
            </div>
            <div data-thumb="/assets/sala/thumbs/IMG_9479.JPG" data-src="/assets/sala/IMG_9479.JPG">
            </div>
            <div data-thumb="/assets/sala/thumbs/IMG_9482.JPG" data-src="/assets/sala/IMG_9482.JPG">
            </div>
        </div><!-- #camera_wrap_2 -->
    </div><!-- .fluid_container -->
    
    <div style="clear:both; display:block; height:50px"></div>
<font style="font-size:18px;font-weight: 400;letter-spacing: 0.05em;text-indent: 25px;"><center>Oferujemy Państwu wynajem sali na imprezy okolicznościowe.<br><br>
Wszystkich informacji dotyczących wynajmu sali udziela<br><font id="osoba">Pani <u>Jadwiga Siniczyn</u></font><br>pod numerem telefonu:<br> 
<font id="osoba">782978957</font>
<br><br>
</center></font>
</div>
</div>