config/routes.rb
Osp::Application.routes.draw do

  resources :videos

  resources :pliks

resources :users, :user_sessions, :news, :images, :statistics, :members, :albums

match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout
match 'logowanie' => 'user_sessions#new', :as => :login
match 'rejestracja' => 'users#new'
match 'about' => 'users_#about'
match 'czlonkowie' => 'users_#czlonkowie'
match 'galeria' => 'users_#galeria'
match 'galeria_wszystkie' => 'albums#galeria_wszystkie'
match 'aktualnosci' => 'news#index'
match 'aktualnosci_grupuj' => 'news#group'
match 'imprezy' => 'news#imprezy'
match 'interwencje' => 'news#interwencje'
match 'statystyki' => 'statistics#index'
match 'szkolenia' => 'news#szkolenia'
match 'inne' => 'news#inne'
match 'otwp' => 'news#otwp'
match 'wynajem_sali' => 'users#wynajem_sali'
match '/ftp/upload' => 'images#create'
match '/pozar_plus' => 'statistics#pozar_plus'
match '/pozar_minus' => 'statistics#pozar_minus'
match '/zagrozenia_plus' => 'statistics#zagrozenia_plus'
match '/zagrozenia_minus' => 'statistics#zagrozenia_minus'
match '/alarmy_plus' => 'statistics#alarmy_plus'
match '/alarmy_minus' => 'statistics#alarmy_minus'

root :to => "users_#start"

end

app/models/album.rb
class Album < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
    if News.find_all_by_id(@album.nr_newsa).count != 0
    @news = News.find(@album.nr_newsa)
    end
    @zdjecia = Image.find_all_by_przydzial(@album.nr_newsa.to_s).sort_by(&:created_at).reverse
    @zdjecia_page = Image.page(params[:page]).per_page(28).order("created_at DESC").find_all_by_przydzial(@album.nr_newsa.to_s)
    @statystyki = Statistic.find_by_rok(Time.now.year)

    respond_to do |format|
      format.html
      format.json { render json: @album }
    end
  end

  def create
    @album_last = Album.last
    @album = Album.new(params[:album])
    if @album_last != nil
    @album.nr_newsa = (10000+@album_last.id)
    else
    @album.nr_newsa = 10000
    end

    respond_to do |format|
      if @album.save
        format.html { redirect_to "/galeria", notice: 'Dodano nowy Album.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
   if current_user
     if (current_user.username == 'Administrator'&&current_user.id==1)||(current_user.username == 'strazak'&&current_user.id==2)
       @album = Album.find(params[:id])
       @album.destroy

       respond_to do |format|
         format.html { redirect_to "/galeria" }
         format.json { head :no_content }
       end
     else
       redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
     end
   else
     redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
   end
  end

  def galeria_wszystkie
    @albums = Album.all.reverse
    @zdjecia = Image.all.sort_by(&:created_at).reverse
    @zdjecia_page = Image.page(params[:page]).per_page(12).order("created_at DESC")
    @statystyki = Statistic.find_by_rok(Time.now.year)

    respond_to do |format|
      format.html
      format.json { render json: @albums }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/galeria_wszystkie.html.erb
			<div class="gallery">
				<div class="gallery_div">
					<h4 style="float:left;">Galeria</h4>
<ul style="float:left;margin-left:20px;height:35px;margin-top:6.5px;">
<%= link_to "Albumy", "/galeria", :class => "zakladki_male" %>
<%= link_to "Wszystkie", "/galeria_wszystkie", :class => "zakladki_male" %>
<%= image_tag("/assets/gplus.png", :height => '47', :width => '42', :class =>"galeriaplus", :onclick => "window.open('https://plus.google.com/101678126146835185818/posts','external');return false;", :title => "Galeria na Picasa Web") %>
</ul>
					<ul>
					<%= will_paginate @zdjecia_page, :container => false %>
					</ul>
				</div>
<% licznik = 0 %>
<% if @zdjecia.count != 0 %>
<div id="myCarousel" class="carousel slide">  
  <!-- Carousel items -->  
  <div class="carousel-inner">  
<% @zdjecia.each do |zdjecia| %>
<% if licznik == 0 %>
    <div class="active item">
	<center>
	<img src="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" style="height:370px;">
	</center>
		<% if (zdjecia.opis != "") && (zdjecia.opis != nil) %>
		<div class="carousel-caption">
                      <p><%= zdjecia.opis %></p>
                </div>
		<% end %>
    </div> 
<% else %>
    <div class="item">
	<center>
	<img src="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" style="height:370px;">
	</center>
		<% if (zdjecia.opis != "") && (zdjecia.opis != nil) %>
		<div class="carousel-caption">
                      <p><%= zdjecia.opis %></p>
                </div>
		<% end %>
    </div> 
<% end %> 
<% licznik += 1 %> 
<% end %>
  </div>  
  <!-- Carousel nav -->  
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>  
  <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>  
</div>  
<% end %>
				<ul class="section">
					<% @zdjecia_page.each do |zdjecia| %>
<a class="fancybox" href="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" title="<%= zdjecia.opis %>" target="_blank">
        <img style="width:185px;height:190px;" src="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" class="img-polaroid"" />
</a>
					<% end %>
				</ul>
			</div>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
			<div class="gallery">
				<div class="gallery_div">
					<% if @news != nil %>
					<% if @news.tytul.length > 48 %>
					<h4>Galeria: <%= @news.tytul[0..40]+".." %></h4>
					<% else %>
					<h4>Galeria: <%= @news.tytul %></h4>
					<% end %>
					<% else %>
					<h4>Galeria</h4>
					<% end %>
					<ul>
					<%= will_paginate @zdjecia_page, :container => false %>
					</ul>
				</div>
<% licznik = 0 %>
<% if @zdjecia.count != 0 %>
<div id="myCarousel" class="carousel slide">  
  <!-- Carousel items -->  
  <div class="carousel-inner">  
<% @zdjecia.each do |zdjecia| %>
<% if licznik == 0 %>
    <div class="active item">
	<center>
	<img src="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" style="height:370px;">
	</center>
		<% if (zdjecia.opis != "") && (zdjecia.opis != nil) %>
		<div class="carousel-caption">
                      <p><%= zdjecia.opis %></p>
                </div>
		<% end %>
    </div> 
<% else %>
    <div class="item">
	<center>
	<img src="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" style="height:370px;">
	</center>
		<% if (zdjecia.opis != "") && (zdjecia.opis != nil) %>
		<div class="carousel-caption">
                      <p><%= zdjecia.opis %></p>
                </div>
		<% end %>
    </div> 
<% end %> 
<% licznik += 1 %> 
<% end %>
  </div>  
  <!-- Carousel nav -->  
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>  
  <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>  
</div>  
<% end %>
				<ul class="section">
					<% @zdjecia_page.each do |zdjecia| %>
<a class="fancybox" href="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" title="<%= zdjecia.opis %>" target="_blank">
        <img style="width:139px;height:134px;" src="http://serwer.osp-lesniewo.pl/<%= zdjecia.nazwa %>" class="img-polaroid"" />
</a>
					<% end %>
				</ul>
				<ul align="center">
					<%= will_paginate @zdjecia_page, :container => false %>
				</ul>
<% if current_user && current_user.username == "Administrator" %>
<div style="margin-top:40px;">
<%= form_tag '/ftp/upload', :method => :post, :multipart => true do %>
<%= text_field_tag :przydzial, @album.nr_newsa, "style"=>"display:none"%>
<center><b><%= label_tag(:q, "Dodaj zdjęcie do aktualności:") %></b>
<%= file_field_tag "file", "style"=>"height:40px;" %>
<%= submit_tag "Dodaj Zdjęcie", "style"=>"width:100px;margin-left:100px;height:40px;cursor:pointer;"%><br>
<div class="field">
    <%= text_area_tag :opis,nil, :class => "images_form_opis", :placeholder => "Krótki opis do zdjęcia..." %>
 </div>
</center>
<% end %>
</div>
<% end %>
			</div>