config/routes.rb
Osp::Application.routes.draw do

  resources :videos

  resources :pliks

resources :users, :user_sessions, :news, :images, :statistics, :members, :albums

match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout
match 'logowanie' => 'user_sessions#new', :as => :login
match 'rejestracja' => 'users#new'
match 'about' => 'users_#about'
match 'czlonkowie' => 'users_#czlonkowie'
match 'galeria' => 'users_#galeria'
match 'galeria_wszystkie' => 'albums#galeria_wszystkie'
match 'aktualnosci' => 'news#index'
match 'aktualnosci_grupuj' => 'news#group'
match 'imprezy' => 'news#imprezy'
match 'interwencje' => 'news#interwencje'
match 'statystyki' => 'statistics#index'
match 'szkolenia' => 'news#szkolenia'
match 'inne' => 'news#inne'
match 'otwp' => 'news#otwp'
match 'wynajem_sali' => 'users#wynajem_sali'
match '/ftp/upload' => 'images#create'
match '/pozar_plus' => 'statistics#pozar_plus'
match '/pozar_minus' => 'statistics#pozar_minus'
match '/zagrozenia_plus' => 'statistics#zagrozenia_plus'
match '/zagrozenia_minus' => 'statistics#zagrozenia_minus'
match '/alarmy_plus' => 'statistics#alarmy_plus'
match '/alarmy_minus' => 'statistics#alarmy_minus'

root :to => "users_#start"

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :nazwa, :opis, :przydzial
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
require 'net/ftp'
  def index
    if current_user
      if (current_user.username == 'Administrator'&&current_user.id==1)||(current_user.username == 'strazak'&&current_user.id==2)
        @images = Image.all
        @statystyki = Statistic.find_by_rok(Time.now.year)

        respond_to do |format|
          format.html
          format.json { render json: @images }
        end
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

  def edit
    if current_user
      if (current_user.username == 'Administrator'&&current_user.id==1)||(current_user.username == 'strazak'&&current_user.id==2)
        @image = Image.find(params[:id])
        @statystyki = Statistic.find_by_rok(Time.now.year)
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

  def create
    if current_user
      if (current_user.username == 'Administrator'&&current_user.id==1)||(current_user.username == 'strazak'&&current_user.id==2)
        file = params[:file]
        if News.find_all_by_id(params[:przydzial]).count != 0
          @news = News.find(params[:przydzial])
          @albums = Album.find_all_by_nr_newsa(@news.id)
        else
          @albums = Album.find_all_by_nr_newsa(params[:przydzial])
        end
        if file != nil && file.original_filename.end_with?('.jpg','.JPG','.png','.PNG','.gif','.GIF')
          @zdjecia = Image.find_all_by_nazwa(file.original_filename).count
          if (@zdjecia == 0)
            file.original_filename = file.original_filename.gsub(/\s+/, "")
            ftp = Net::FTP.new('s3.masternet.pl')
            ftp.passive = true
            ftp.login(user = ENV['ftp_login'], passwd = ENV['ftp_haslo'])
            ftp.storbinary("STOR " + file.original_filename, StringIO.new(file.read), Net::FTP::DEFAULT_BLOCKSIZE)
            ftp.quit()
            @image = Image.new
            @image.nazwa = file.original_filename
            @image.opis = params[:opis]
            @image.przydzial = params[:przydzial]
            if @albums.count == 0
              @album = Album.new
              @album.tytul = @news.tytul
              @album.nr_newsa = @news.id
              @album.save
            end

            respond_to do |format|
              if @image.save
                format.html { redirect_to @news, notice: 'Gratulacje! Dodano zdj&#281;cie do aktualno&#347;ci' }
                format.json { render json: @image, status: :created, location: @image }
              else
                format.html { redirect_to @news, notice: 'Uwaga! Niepowodznie dodania zdjecia' }
                format.json { render json: @image.errors, status: :unprocessable_entity }
              end
            end
          else
            redirect_to @news, :notice => 'Uwaga! Zdj&#281;cie o takiej nazwie ju&#380; jest w bazie!'
          end
        else
          redirect_to @news, :notice => 'Uwaga! Nie wybrano zdj&#281cia z komputera lub rozszerzenie jest nieprawid&#322owe!'
        end
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

  def update
    if current_user
      if (current_user.username == 'Administrator'&&current_user.id==1)||(current_user.username == 'strazak'&&current_user.id==2)
        @image = Image.find(params[:id])

        respond_to do |format|
          if @image.update_attributes(params[:image])
            format.html { redirect_to "/galeria", notice: 'Gratulacje! Zdj&#281;cie zaktualizowano' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @image.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end

  def destroy
    if current_user
      if (current_user.username == 'Administrator'&&current_user.id==1)||(current_user.username == 'strazak'&&current_user.id==2)
        @image = Image.find(params[:id])
        @image.destroy

        respond_to do |format|
          format.html { redirect_to images_url }
          format.json { head :no_content }
        end
      else
        redirect_to root_url, :notice => 'Uwaga! Nie masz uprawnie&#324;!'
      end
    else
      redirect_to :login, :notice => 'Informacja! Zaloguj si&#281; aby obejrze&#263;!'
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br />
    <%= f.text_field :nazwa %>
  </div>
  <div class="field">
    <%= f.label :opis %><br />
    <%= f.text_area :opis %>
  </div>
  <div class="field">
    <%= f.label :przydzial %><br />
    <%= f.text_field :przydzial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class="home">
<h4>Lista Wszystkich Zdjęć</h4>
<div style="background: none repeat scroll 0% 0% rgb(116, 149, 150);color:black;padding: 5px 19px 0px 18px;">

<% @images.each do |image| %>
<div class="lista_zdjec">
<center>
<div style="width:85px;">
<img src="http://serwer.osp-lesniewo.pl/<%= image.nazwa %>" class="img-rounded"" title="<%= image.nazwa %>"/>
</div>
<% if current_user && ((current_user.username == "Administrator" && current_user.id == 1)||(current_user.username == "strazak"&& current_user.id == 2)) %>
<%= link_to 'Edytuj', edit_image_path(image) %> | <%= link_to 'Usuń', image, method: :delete, data: { confirm: 'Napewno chcesz usunąć to zjdęcie?' } %>
<% end %>
</center>
</div>
<% end %>
</div>
<form>
<input name="commit" style="height:15.4px;width:100px;font-weight:bold;cursor:pointer;" value=" Wróć do listy" onclick="location.href = '/aktualnosci'">
</form>
</div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nazwa:</b>
  <%= @image.nazwa %>
</p>

<p>
  <b>Opis:</b>
  <%= @image.opis %>
</p>

<p>
  <b>Przydzial:</b>
  <%= @image.przydzial %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>