config/routes.rb
Osp::Application.routes.draw do

  resources :videos

  resources :pliks

resources :users, :user_sessions, :news, :images, :statistics, :members, :albums

match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout
match 'logowanie' => 'user_sessions#new', :as => :login
match 'rejestracja' => 'users#new'
match 'about' => 'users_#about'
match 'czlonkowie' => 'users_#czlonkowie'
match 'galeria' => 'users_#galeria'
match 'galeria_wszystkie' => 'albums#galeria_wszystkie'
match 'aktualnosci' => 'news#index'
match 'aktualnosci_grupuj' => 'news#group'
match 'imprezy' => 'news#imprezy'
match 'interwencje' => 'news#interwencje'
match 'statystyki' => 'statistics#index'
match 'szkolenia' => 'news#szkolenia'
match 'inne' => 'news#inne'
match 'otwp' => 'news#otwp'
match 'wynajem_sali' => 'users#wynajem_sali'
match '/ftp/upload' => 'images#create'
match '/pozar_plus' => 'statistics#pozar_plus'
match '/pozar_minus' => 'statistics#pozar_minus'
match '/zagrozenia_plus' => 'statistics#zagrozenia_plus'
match '/zagrozenia_minus' => 'statistics#zagrozenia_minus'
match '/alarmy_plus' => 'statistics#alarmy_plus'
match '/alarmy_minus' => 'statistics#alarmy_minus'

root :to => "users_#start"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OSP Leśniewo</title>
  <link href="/logo.png" rel="icon" type="image/x-icon">
  <%= auto_discovery_link_tag(:atom, news_path(:atom)) %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
  $(document).ready(function() {
    $(".fancybox")
    .attr('rel', 'gallery')
    .fancybox({
      beforeShow: function () {
        $('<div class="watermark"></div>')
        .bind("contextmenu", function (e) {
          return false;
        })
      .prependTo( $.fancybox.inner );
      }
    });
  });
  </script>
</head>
<body>
  <%= render "shared/notice" %>

  <% if current_page?(:controller => 'users_', :action => 'start') %>
    <div class="page page-home">
  <% elsif current_page?(:controller => 'users_', :action => 'about') %>
    <div class="page page-about">
  <% elsif current_page?(:controller => 'users_', :action => 'czlonkowie') %>
    <div class="page page-news">
  <% else %>
    <div class="page page-contact">
  <% end %>
    <div class="header">
      <div>
        <%= image_tag("herb.png", :class => "logo_herb") %>
        <div style="margin-bottom:-37px;margin-top:-13px;">
          <font style="color:white;font-family: 'Exo', sans-serif;font-size:40px;line-height:50px;">OCHOTNICZA STRAŻ POŻARNA <br>
          <font style="color:red">w LEŚNIEWIE</font></font><span>Bogu na chwałę, ludziom na pożytek</span>
        </div>
        <%= render "shared/menu" %>
        <% if (current_page?("/"))||(current_page?("/about"))||(current_page?("/czlonkowie"))||(current_page?("/wynajem_sali")) %>
          <div class="featured">
            <h3>TEL. ALARMOWY 998 lub 112</h3>
            <% if current_page?(:controller => 'users_', :action => 'about') %>
              <br><br><br><br>
              <%= link_to "Kontakt >>", "#kontakt", "data-toggle"=>"modal" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="body">
      <%= yield %>
      <div class="sidebar">
        <div style="margin-top:-20px;float:right;color:white;"><%= I18n.l Time.now, :format => "%A, %B %d, %Y" %></div>
        <%= render "shared/statistics" %>
        <%= render "shared/calendar" %>
        <%= render "shared/weather" %>
      </div>
      <div class="section">
        <div>
          <h4>Galeria</h4>
          <ul>
            <% footer_images.each do |zdjecia| %>
              <li><%= link_to("/galeria") do %><%= image_tag("http://serwer.osp-lesniewo.pl/#{zdjecia.nazwa}", "style"=>"height:115px;width:175px;") %><% end %></li>
            <% end %>
          </ul>
        </div>
        <div class="connect">
          <h4>Linki</h4>
          <%= link_to("http://www.kppsp.puck.pl/", "target"=>"_blank") do %>
            <%= image_tag("psp.png") %>
          <% end %>
          <%= link_to("http://www.zosprp.pl/", "target"=>"_blank") do %>
            <%= image_tag("zosp.png") %>
          <% end %>
          <%= link_to("http://www.tartak-mika.pl/", "target"=>"_blank") do %>
            <%= image_tag("mika.png","style"=> "margin-left: 0px !important;") %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="footer">
      <div>
        <ul>
          <li><%= link_to "Start", "/" %></li>
          <li><%= link_to "O nas", "/about" %></li>
          <li>
            <% if current_user %>
              <%= current_user.username %>
              <%= link_to "Wyloguj", :logout %>
            <% else %>
                <%= link_to "Logowanie", :login %>
            <% end %>
          </li>
          <li><%= link_to "Kontakt", "#kontakt", "data-toggle"=>"modal" %></li>
          <% if current_user && ((current_user.username == "Administrator" && current_user.id == 1)||(current_user.username == "strazak"&& current_user.id == 2)) %>
            <%= link_to 'Dodaj News', new_news_path %> | 
            <%= link_to 'Lista Zdjęć', images_path %> |
            <%= link_to 'Lista Plików', pliks_path %>
          <% else %>
              <iframe src="http://www.facebook.com/plugins/like.php?href=http://osp-lesniewo.pl&layout=standard&show_faces=false&2.width=250&action=like&colorscheme=dark" scrolling="no" frameborder="0" allowTransparency="true" style="border:none; overflow:hidden; width:70px; height:25px; margin-right:10px;">3.</iframe>
              <div class="g-plusone" data-href="http://osp-lesniewo.pl/" data-annotation="none"></div>
          <% end %>
        </ul>
        <p>
          Copyright &#169; <%= Time.now.year %>. OSP Leśniewo all rights reserved.
        </p>
      </div>
    </div>
    <div style="margin-top:-50px">
      <center>Projekt <%= link_to "Miłosz Osiński", "http://m1l05z.pl" %> i <%= link_to "Krystian Hallmann", "http://khallmann.pl" %></center>
    </div>
  </div>
  <%= render "shared/contact_modal" %>
</body>
<script type="text/javascript">
  window.___gcfg = {lang: 'pl'};
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
</html>